import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import "../globals.css";
import { getMessages } from 'next-intl/server';
import { Poppins } from 'next/font/google';
import { Almarai } from 'next/font/google';
import BackToTop from '../components/backToTop';
// English font
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400', '500', '600', '700','800','900'],
  variable: '--font-poppins',
});


// Arabic font
const almarai = Almarai({
  subsets: ['arabic'],
  weight: ['400', '700'],
  variable: '--font-almarai',
});


export const metadata = {
  title: "AVS",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await getMessages();
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

   const fontClass = locale === 'ar' ? almarai.className : poppins.className;
  return (
    <html lang={locale}>
      <body
         dir={locale === "ar" ? "rtl" : "ltr"}
        className={`${fontClass} antialiased bg-black h-[400vh]`}
      >
        <NextIntlClientProvider messages={messages} locale={locale} >
          {children}
          <BackToTop/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
